[[headers]]
  for = "/*.pdf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Range"
    Access-Control-Expose-Headers = "Accept-Ranges, Content-Encoding, Content-Length, Content-Range"
